"""Standalone terms-of-service page renderer."""

from __future__ import annotations


def render_terms() -> str:
    """Render the local app's concise terms of service."""
    return """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Terms of Service · Capital Gain Estimate Tax Calculator</title><style>
    :root { color-scheme:light; --ink:#102a43; --muted:#627d98; --paper:#f4f7fa; --line:#d9e2ec; --navy:#15324b; --blue:#1f5f8b; } * { box-sizing:border-box } body { margin:0; background:var(--paper); color:var(--ink); font:16px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif } header { background:var(--navy); color:white; padding:32px max(24px,calc((100vw - 800px)/2)) } header p { margin:4px 0 0; color:#c7d7e6 } h1 { margin:0; font-size:28px } main { max-width:800px; margin:28px auto 48px; padding:28px; background:white; border:1px solid var(--line); border-radius:12px; box-shadow:0 1px 2px #102a4310 } h2 { margin:28px 0 8px; font-size:19px } h2:first-of-type { margin-top:24px } p { margin:8px 0 } .muted { color:var(--muted) } a { color:var(--blue); font-weight:700 } footer { max-width:800px; margin:-28px auto 36px; color:var(--muted); text-align:center; font-size:13px }
    </style></head><body><header><h1>Terms of Service</h1><p>Capital Gain Estimate Tax Calculator</p></header><main><p class="muted">Last updated: September 22, 2026</p><p>Capital Gain Estimate Tax Calculator is developed by <strong>DC Technology Consulting</strong> and is provided for open-source, free use.</p><h2>Permitted use</h2><p>You may use, copy, modify, and share this software at no cost. Keep this notice with material redistributions.</p><h2>Important limitations</h2><p>This software is an informational tool. It is not tax, legal, accounting, or investment advice. You are responsible for reviewing all imported data, calculations, tax rates, generated reports, and any payment decisions with qualified professionals where appropriate.</p><p>Bundled tax-rule data and payment-site links are provided for convenience only. Confirm current rules, amounts, deadlines, and official payment destinations before acting.</p><p>DC Technology Consulting assumes no liability or responsibility for your use of the calculator or for any action taken or not taken based on its output.</p><h2>Third-party services</h2><p>Government payment websites and other external links have their own terms, privacy practices, and availability.</p><h2>Changes</h2><p>These terms may be updated with future releases. Continued use after an update means you accept the revised terms.</p><p><a href="/">Return to dashboard</a></p></main><footer>Developed by DC Technology Consulting · Open-source, free use</footer></body></html>"""
